spring:
  application:
    name: server-cache
  profiles:
    default: local

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.ali.server.cache: DEBUG

cache:
  expire-after-write: ${CACHE_EXPIRE_AFTER_WRITE:1000}
  initial-capacity: ${CACHE_INITIAL_CAPACITY:1000}

mongo:
  database: ${MONGO_DATABASE:server-cache-mongo}
  username: ${MONGO_USERNAME:appUser}
  password: ${MONGO_PASSWORD:appPass}
  auth-db: ${MONGO_AUTH_DB:admin}
  max-pool-size: ${MONGO_MAX_POOL_SIZE:50}
  min-pool-size: ${MONGO_MIN_POOL_SIZE:5}